// 产品列表
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST' // 发送请求
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS' // 请求成功
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL' // 请求失败

// 产品详情
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'
